-- SE ASIGNA 'VARIUS' COMO REMPLAZANTE DE NULL DE LA COLUMNA CLASSID DE LA TABLA 'product'.

UPDATE product
SET CLASSID = 'VARIUS'
WHERE CLASSID IS NULL;

-- SE ASIGNA 'VARIUS' COMO REMPLAZANTE DE NULL DE LA COLUMNA CLASSID DE LA TABLA 'betting'.
UPDATE betting
SET CLASSID = 'VARIUS'
WHERE CLASSID IS NULL;

UPDATE betting
SET Product = 'Sportsbook'
WHERE Product LIKE 'Varius';

ALTER TABLE account MODIFY AccountNo VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE betting MODIFY AccountNo VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;


